import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

type Settings = { name?: string; phone?: string; address?: string; short_description?: string; is_public_profile_enabled?: boolean; is_marketplace_visible?: boolean };
type Onboarding = { business_name?: string; is_onboarding_completed?: boolean; onboarding_step?: string };
const copy = {
  hy: { title: 'Կառավարում', subtitle: 'Բիզնեսի էջ և սկզբնական կարգավորում', setup: 'Ավարտեք բիզնեսի կարգավորումը', setupHint: 'Ավելացրեք առաջին ծառայությունը, ապա հրապարակեք բիզնեսը։', service: 'Առաջին ծառայության անուն', duration: 'Տևողություն՝ րոպե', price: 'Գին՝ ֏', add: 'Ավելացնել ծառայությունը', complete: 'Ավարտել և հրապարակել', profile: 'Բիզնեսի տվյալներ', phone: 'Հեռախոս', address: 'Հասցե', description: 'Կարճ նկարագրություն', publicProfile: 'Հանրային էջ', marketplace: 'Ցուցադրել որոնման մեջ', save: 'Պահպանել փոփոխությունները', saved: 'Փոփոխությունները պահպանված են', failed: 'Գործողությունը չհաջողվեց', logout: 'Դուրս գալ բիզնես հաշվից' },
  ru: { title: 'Управление', subtitle: 'Страница бизнеса и первоначальная настройка', setup: 'Завершите настройку бизнеса', setupHint: 'Добавьте первую услугу, затем опубликуйте бизнес.', service: 'Название первой услуги', duration: 'Длительность, минуты', price: 'Цена, ֏', add: 'Добавить услугу', complete: 'Завершить и опубликовать', profile: 'Данные бизнеса', phone: 'Телефон', address: 'Адрес', description: 'Краткое описание', publicProfile: 'Публичная страница', marketplace: 'Показывать в поиске', save: 'Сохранить изменения', saved: 'Изменения сохранены', failed: 'Не удалось выполнить действие', logout: 'Выйти из бизнес-аккаунта' },
  en: { title: 'Management', subtitle: 'Business profile and initial setup', setup: 'Finish business setup', setupHint: 'Add your first service, then publish the business.', service: 'First service name', duration: 'Duration, minutes', price: 'Price, ֏', add: 'Add service', complete: 'Finish and publish', profile: 'Business details', phone: 'Phone', address: 'Address', description: 'Short description', publicProfile: 'Public profile', marketplace: 'Show in search', save: 'Save changes', saved: 'Changes saved', failed: 'The action failed', logout: 'Sign out of business account' },
};
const managementCopy = {
  hy: { services: 'Ծառայությունների կառավարում', addService: 'Ավելացնել նոր ծառայություն', staff: 'Աշխատակիցներ', staffHint: 'Աշխատակիցը կստանա սեփական business մուտքը։', staffName: 'Աշխատակցի անուն', staffEmail: 'Էլ․ փոստ', staffPhone: 'Հեռախոս', staffPassword: 'Ժամանակավոր գաղտնաբառ՝ 8+ նիշ', addStaff: 'Ավելացնել աշխատակից', created: 'Հաջողությամբ ավելացված է' },
  ru: { services: 'Управление услугами', addService: 'Добавить новую услугу', staff: 'Сотрудники', staffHint: 'Сотрудник получит собственный вход в бизнес-аккаунт.', staffName: 'Имя сотрудника', staffEmail: 'Эл. почта', staffPhone: 'Телефон', staffPassword: 'Временный пароль — 8+ символов', addStaff: 'Добавить сотрудника', created: 'Успешно добавлено' },
  en: { services: 'Service management', addService: 'Add a new service', staff: 'Team members', staffHint: 'The team member receives their own business sign-in.', staffName: 'Team member name', staffEmail: 'Email', staffPhone: 'Phone', staffPassword: 'Temporary password — 8+ characters', addStaff: 'Add team member', created: 'Added successfully' },
};

export default function BusinessAdmin() {
  const { locale, theme } = useApp(); const c = copy[locale]; const m = managementCopy[locale]; const client = useQueryClient();
  const settingsQuery = useQuery<Settings>({ queryKey: ['business-settings'], queryFn: businessApi.settings, retry: false });
  const onboardingQuery = useQuery<Onboarding>({ queryKey: ['business-onboarding'], queryFn: businessApi.onboardingStatus, retry: false });
  const [form, setForm] = useState({ phone: '', address: '', short_description: '', is_public_profile_enabled: false, is_marketplace_visible: false });
  const [service, setService] = useState({ name: '', duration: '60', price: '' }); const [serviceAdded, setServiceAdded] = useState(false);
  const [staff, setStaff] = useState({ name: '', email: '', phone: '', password: '' });
  useEffect(() => { const value = settingsQuery.data; if (value) {
    // The form intentionally takes a fresh server snapshot after each refetch.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setForm({ phone: value.phone ?? '', address: value.address ?? '', short_description: value.short_description ?? '', is_public_profile_enabled: !!value.is_public_profile_enabled, is_marketplace_visible: !!value.is_marketplace_visible });
  } }, [settingsQuery.data]);
  const fail = (error: unknown) => Alert.alert(c.failed, apiErrorMessage(error));
  const save = useMutation({ mutationFn: () => businessApi.updateSettings(form), onSuccess: () => { void client.invalidateQueries({ queryKey: ['business-settings'] }); Alert.alert(c.saved); }, onError: fail });
  const addService = useMutation({ mutationFn: () => businessApi.createService({ name: service.name.trim(), duration_minutes: Number(service.duration), price: service.price ? Number(service.price) : 0, currency: 'AMD' }), onSuccess: () => { setServiceAdded(true); void client.invalidateQueries({ queryKey: ['business-services'] }); void client.invalidateQueries({ queryKey: ['business-onboarding'] }); }, onError: fail });
  const addStaff = useMutation({ mutationFn: () => businessApi.createStaff({ name: staff.name.trim(), email: staff.email.trim().toLowerCase(), phone: staff.phone.trim() || undefined, password: staff.password }), onSuccess: () => { setStaff({ name: '', email: '', phone: '', password: '' }); void client.invalidateQueries({ queryKey: ['business-staff'] }); Alert.alert(m.created); }, onError: fail });
  const complete = useMutation({ mutationFn: businessApi.completeOnboarding, onSuccess: () => { void client.invalidateQueries(); router.replace('/(business)/today'); }, onError: fail });
  const logout = useMutation({ mutationFn: businessApi.logout, onSuccess: () => router.replace('/(business)/login') });
  const onboarding = onboardingQuery.data; const incomplete = onboarding ? !onboarding.is_onboarding_completed : false; const serviceReady = serviceAdded || onboarding?.onboarding_step !== 'services';
  const input = (key: 'phone' | 'address' | 'short_description', placeholder: string) => <TextInput value={form[key]} onChangeText={(value) => setForm((current) => ({ ...current, [key]: value }))} placeholder={placeholder} placeholderTextColor={theme.muted} multiline={key === 'short_description'} style={[styles.input, key === 'short_description' && styles.multiline, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} />;
  if (settingsQuery.isLoading || onboardingQuery.isLoading) return <SafeAreaView style={[styles.screen, styles.center, { backgroundColor: theme.background }]}><ActivityIndicator color={theme.plum} /></SafeAreaView>;

  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View style={[styles.icon, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="gearshape.fill" android="settings" color={theme.plum} size={25} /></View><View style={styles.headerText}><Text style={[styles.title, { color: theme.text }]}>{c.title}</Text><Text style={[styles.subtitle, { color: theme.muted }]}>{c.subtitle}</Text></View></View>
    {incomplete && <View style={[styles.card, { backgroundColor: theme.plumSoft, borderColor: theme.peach }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{c.setup}</Text><Text style={[styles.hint, { color: theme.muted }]}>{c.setupHint}</Text>{!serviceReady && <><TextInput value={service.name} onChangeText={(name) => setService((current) => ({ ...current, name }))} placeholder={c.service} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.surfaceRaised }]} /><View style={styles.row}><TextInput value={service.duration} onChangeText={(duration) => setService((current) => ({ ...current, duration }))} placeholder={c.duration} keyboardType="number-pad" placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border, backgroundColor: theme.surfaceRaised }]} /><TextInput value={service.price} onChangeText={(price) => setService((current) => ({ ...current, price }))} placeholder={c.price} keyboardType="number-pad" placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border, backgroundColor: theme.surfaceRaised }]} /></View><Pressable disabled={!service.name.trim() || addService.isPending} onPress={() => addService.mutate()} style={[styles.primary, { backgroundColor: theme.plum, opacity: service.name.trim() ? 1 : 0.4 }]}>{addService.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{c.add}</Text>}</Pressable></>}{serviceReady && <Pressable onPress={() => complete.mutate()} style={[styles.primary, { backgroundColor: theme.plum }]}>{complete.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{c.complete}</Text>}</Pressable>}</View>}
    <View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{settingsQuery.data?.name ?? onboarding?.business_name ?? c.profile}</Text><Text style={[styles.eyebrow, { color: theme.gold }]}>{c.profile}</Text>{input('phone', c.phone)}{input('address', c.address)}{input('short_description', c.description)}<View style={styles.toggle}><Text style={[styles.toggleLabel, { color: theme.text }]}>{c.publicProfile}</Text><Switch value={form.is_public_profile_enabled} onValueChange={(value) => setForm((current) => ({ ...current, is_public_profile_enabled: value }))} trackColor={{ false: theme.border, true: theme.plum }} /></View><View style={styles.toggle}><Text style={[styles.toggleLabel, { color: theme.text }]}>{c.marketplace}</Text><Switch value={form.is_marketplace_visible} onValueChange={(value) => setForm((current) => ({ ...current, is_marketplace_visible: value }))} trackColor={{ false: theme.border, true: theme.plum }} /></View><Pressable onPress={() => save.mutate()} style={[styles.primary, { backgroundColor: theme.plum }]}>{save.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{c.save}</Text>}</Pressable></View>
    {!incomplete && <View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{m.services}</Text><TextInput value={service.name} onChangeText={(name) => setService((current) => ({ ...current, name }))} placeholder={c.service} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><View style={styles.row}><TextInput value={service.duration} onChangeText={(duration) => setService((current) => ({ ...current, duration }))} placeholder={c.duration} keyboardType="number-pad" placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><TextInput value={service.price} onChangeText={(price) => setService((current) => ({ ...current, price }))} placeholder={c.price} keyboardType="number-pad" placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /></View><Pressable disabled={!service.name.trim() || addService.isPending} onPress={() => addService.mutate()} style={[styles.primary, { backgroundColor: theme.plum, opacity: service.name.trim() ? 1 : 0.4 }]}>{addService.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{m.addService}</Text>}</Pressable></View>}
    <View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.sectionTitle, { color: theme.text }]}>{m.staff}</Text><Text style={[styles.hint, { color: theme.muted }]}>{m.staffHint}</Text><TextInput value={staff.name} onChangeText={(name) => setStaff((current) => ({ ...current, name }))} placeholder={m.staffName} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><TextInput value={staff.email} onChangeText={(email) => setStaff((current) => ({ ...current, email }))} placeholder={m.staffEmail} keyboardType="email-address" autoCapitalize="none" placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><TextInput value={staff.phone} onChangeText={(phone) => setStaff((current) => ({ ...current, phone }))} placeholder={m.staffPhone} keyboardType="phone-pad" placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><TextInput value={staff.password} onChangeText={(password) => setStaff((current) => ({ ...current, password }))} placeholder={m.staffPassword} secureTextEntry placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} /><Pressable disabled={staff.name.trim().length < 2 || !/^\S+@\S+\.\S+$/.test(staff.email) || staff.password.length < 8 || addStaff.isPending} onPress={() => addStaff.mutate()} style={[styles.primary, { backgroundColor: theme.plum, opacity: staff.name.trim().length >= 2 && /^\S+@\S+\.\S+$/.test(staff.email) && staff.password.length >= 8 ? 1 : 0.4 }]}>{addStaff.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{m.addStaff}</Text>}</Pressable></View>
    <Pressable onPress={() => logout.mutate()} style={[styles.logout, { borderColor: theme.border }]}><VizitIcon ios="rectangle.portrait.and.arrow.right" android="logout" color={theme.danger} size={19} /><Text style={{ color: theme.danger, fontWeight: '800' }}>{c.logout}</Text></Pressable>
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center' }, content: { padding: 18, paddingBottom: 34, gap: 14 }, header: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingVertical: 8 }, icon: { width: 52, height: 52, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, headerText: { flex: 1 }, title: { fontSize: 27, fontWeight: '900', letterSpacing: -0.6 }, subtitle: { fontSize: 12, marginTop: 3 }, card: { padding: 16, borderRadius: 22, borderWidth: 1, gap: 11 }, sectionTitle: { fontSize: 19, fontWeight: '900' }, eyebrow: { fontSize: 10, fontWeight: '900', letterSpacing: 1, textTransform: 'uppercase' }, hint: { fontSize: 13, lineHeight: 19 }, input: { minHeight: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 14 }, multiline: { height: 84, paddingTop: 14, textAlignVertical: 'top' }, row: { flexDirection: 'row', gap: 9 }, flex: { flex: 1 }, primary: { height: 53, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: '#FFF', fontWeight: '900', fontSize: 14 }, toggle: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, toggleLabel: { flex: 1, fontWeight: '700' }, logout: { height: 54, borderWidth: 1, borderRadius: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 } });
