import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';

const copy = { hy: ['Վերլուծություն', 'Այսօր ամրագրումներ', 'Այսօր եկամուտ', '7 օր՝ ամրագրումներ', '7 օր՝ եկամուտ', 'Միջին կտրոն', 'Ավարտման տոկոս'], ru: ['Аналитика', 'Записи сегодня', 'Доход сегодня', 'Записи за 7 дней', 'Доход за 7 дней', 'Средний чек', 'Завершение'], en: ['Analytics', 'Bookings today', 'Revenue today', '7-day bookings', '7-day revenue', 'Average ticket', 'Completion rate'] };
const get = (data: unknown, path: string): number => { const value = path.split('.').reduce<unknown>((v, key) => v && typeof v === 'object' ? (v as Record<string, unknown>)[key] : undefined, data); return Number(value ?? 0); };
export default function AnalyticsScreen() { const { locale, theme } = useApp(); const c = copy[locale]; const query = useQuery({ queryKey: ['business-analytics'], queryFn: businessApi.analytics, retry: false }); const metrics = [[c[1], get(query.data, 'today.bookings')], [c[2], get(query.data, 'today.revenue')], [c[3], get(query.data, 'last_7_days.bookings')], [c[4], get(query.data, 'last_7_days.revenue')], [c[5], get(query.data, 'metrics_30d.avg_ticket')], [c[6], `${get(query.data, 'metrics_30d.completion_rate')}%`]]; return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: theme.text }]}>{c[0]}</Text>{query.isLoading ? <ActivityIndicator color={theme.plum} /> : <View style={styles.grid}>{metrics.map(([label, value]) => <View key={String(label)} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.value, { color: theme.plumStrong }]}>{String(value)}</Text><Text style={{ color: theme.muted, fontWeight: '700' }}>{label}</Text></View>)}</View>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18 }, title: { fontSize: 28, fontWeight: '900', marginBottom: 20 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, card: { width: '48%', minHeight: 118, padding: 15, borderRadius: 11, borderWidth: 1, justifyContent: 'space-between' }, value: { fontSize: 25, fontWeight: '900' } });
