import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
const copy = { hy: ['Պլան և վճարումներ', 'Վճարման կարգավիճակ', 'Ընթացիկ պլան', 'Բաժանորդագրություն', 'Վերջին հաշիվ', 'IDBank պայմանագրից հետո վճարումները կակտիվացվեն։'], ru: ['Тариф и платежи', 'Статус оплаты', 'Текущий тариф', 'Подписка', 'Последний счёт', 'Платежи будут активированы после договора с IDBank.'], en: ['Plan and billing', 'Billing status', 'Current plan', 'Subscription', 'Latest invoice', 'Payments will be enabled after the IDBank merchant agreement.'] };
const show = (v: unknown) => v == null ? '—' : String(v);
export default function BillingScreen() { const { locale, theme } = useApp(); const c = copy[locale]; const query = useQuery({ queryKey: ['business-billing'], queryFn: businessApi.billing, retry: false }); const data = query.data as Record<string, unknown> | undefined; const subscription = data?.subscription as Record<string, unknown> | undefined; const invoice = data?.latest_invoice as Record<string, unknown> | undefined; return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: theme.text }]}>{c[0]}</Text>{query.isLoading ? <ActivityIndicator color={theme.plum} /> : <><View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.label, { color: theme.muted }]}>{c[1]}</Text><Text style={[styles.value, { color: theme.text }]}>{show(data?.billing_status)}</Text><Text style={[styles.label, { color: theme.muted }]}>{c[2]}</Text><Text style={[styles.value, { color: theme.plum }]}>{show(subscription?.plan_name ?? subscription?.plan_code)}</Text><Text style={[styles.label, { color: theme.muted }]}>{c[3]}</Text><Text style={[styles.value, { color: theme.text }]}>{show(subscription?.status)}</Text></View>{invoice && <View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.label, { color: theme.muted }]}>{c[4]}</Text><Text style={[styles.amount, { color: theme.text }]}>{show(invoice.amount)} {show(invoice.currency)}</Text><Text style={{ color: theme.gold, fontWeight: '900' }}>{show(invoice.status)}</Text></View>}<Text style={[styles.note, { color: theme.muted, backgroundColor: theme.plumSoft }]}>{c[5]}</Text></>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 12 }, title: { fontSize: 28, fontWeight: '900', marginBottom: 8 }, card: { borderWidth: 1, borderRadius: 11, padding: 16, gap: 7 }, label: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', marginTop: 5 }, value: { fontSize: 18, fontWeight: '900' }, amount: { fontSize: 25, fontWeight: '900' }, note: { padding: 14, borderRadius: 10, lineHeight: 20 } });
