import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

const copy = { hy: { title: 'Հաճախորդի քարտ', contact: 'Կոնտակտներ', history: 'Այցերի պատմություն', stats: 'Վիճակագրություն', name: 'Անուն', phone: 'Հեռախոս', email: 'Էլ․ փոստ', vip: 'VIP հաճախորդ', save: 'Պահպանել', bookings: 'Ամրագրումներ', spent: 'Ծախսել է', completed: 'Ավարտված', empty: 'Այցեր դեռ չկան' }, ru: { title: 'Карточка клиента', contact: 'Контакты', history: 'История визитов', stats: 'Статистика', name: 'Имя', phone: 'Телефон', email: 'Email', vip: 'VIP-клиент', save: 'Сохранить', bookings: 'Записи', spent: 'Потрачено', completed: 'Завершено', empty: 'Визитов пока нет' }, en: { title: 'Client card', contact: 'Contacts', history: 'Visit history', stats: 'Statistics', name: 'Name', phone: 'Phone', email: 'Email', vip: 'VIP client', save: 'Save', bookings: 'Bookings', spent: 'Total spent', completed: 'Completed', empty: 'No visits yet' } };
export default function ClientDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const clientId = Number(id); const { locale, theme } = useApp(); const c = copy[locale]; const qc = useQueryClient();
  const query = useQuery({ queryKey: ['business-client', clientId], queryFn: () => businessApi.client(clientId), enabled: Number.isFinite(clientId) });
  const [form, setForm] = useState({ name: '', phone: '', email: '', is_vip: false });
  useEffect(() => { if (query.data) {
    // Reset the editable draft when a fresh client snapshot arrives.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setForm({ name: query.data.name ?? '', phone: query.data.phone ?? '', email: query.data.email ?? '', is_vip: !!query.data.is_vip });
  } }, [query.data]);
  const save = useMutation({ mutationFn: () => businessApi.updateClient(clientId, { ...form, email: form.email || undefined }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['business-client', clientId] }); void qc.invalidateQueries({ queryKey: ['business-clients'] }); Alert.alert(c.save, '✓'); }, onError: (e) => Alert.alert(c.save, apiErrorMessage(e)) });
  if (query.isLoading) return <SafeAreaView style={[styles.center, { backgroundColor: theme.background }]}><ActivityIndicator color={theme.plum} /></SafeAreaView>;
  const data = query.data;
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { borderColor: theme.border }]}><VizitIcon ios="chevron.left" android="arrow_back" color={theme.text} size={21} /></Pressable><View><Text style={[styles.title, { color: theme.text }]}>{data?.name ?? c.title}</Text><Text style={{ color: theme.muted }}>{c.title}</Text></View></View><View style={styles.stats}><Stat value={data?.bookings_count ?? 0} label={c.bookings} /><Stat value={`${data?.total_spent ?? 0} ֏`} label={c.spent} /><Stat value={data?.crm?.completed_count ?? 0} label={c.completed} /></View><View style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.section, { color: theme.text }]}>{c.contact}</Text>{(['name', 'phone', 'email'] as const).map((key) => <TextInput key={key} value={form[key]} onChangeText={(v) => setForm((f) => ({ ...f, [key]: v }))} placeholder={c[key]} placeholderTextColor={theme.muted} keyboardType={key === 'phone' ? 'phone-pad' : key === 'email' ? 'email-address' : 'default'} autoCapitalize={key === 'email' ? 'none' : undefined} style={[styles.input, { color: theme.text, borderColor: theme.border, backgroundColor: theme.background }]} />)}<View style={styles.toggle}><Text style={{ color: theme.text, fontWeight: '800' }}>{c.vip}</Text><Switch value={form.is_vip} onValueChange={(v) => setForm((f) => ({ ...f, is_vip: v }))} trackColor={{ false: theme.border, true: theme.plum }} /></View><Pressable onPress={() => save.mutate()} style={[styles.primary, { backgroundColor: theme.plum }]}>{save.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c.save}</Text>}</Pressable></View><Text style={[styles.section, { color: theme.text }]}>{c.history}</Text>{data?.recent_bookings?.length ? data.recent_bookings.map((booking) => <View key={booking.id} style={[styles.visit, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={{ flex: 1 }}><Text style={{ color: theme.text, fontWeight: '900' }}>{booking.service?.name ?? '—'}</Text><Text style={{ color: theme.muted, marginTop: 4 }}>{booking.starts_at?.slice(0, 16)} · {booking.staff?.name ?? '—'}</Text></View><Text style={{ color: theme.plum, fontWeight: '800' }}>{booking.status}</Text></View>) : <Text style={{ color: theme.muted }}>{c.empty}</Text>}</ScrollView></SafeAreaView>;
}
function Stat({ value, label }: { value: string | number; label: string }) { const { theme } = useApp(); return <View style={[styles.stat, { backgroundColor: theme.plumSoft }]}><Text style={[styles.statValue, { color: theme.plum }]}>{value}</Text><Text style={[styles.statLabel, { color: theme.muted }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: 18, paddingBottom: 44, gap: 13 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 43, height: 43, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 24, fontWeight: '900' }, stats: { flexDirection: 'row', gap: 7 }, stat: { flex: 1, padding: 10, minHeight: 72, justifyContent: 'center', borderRadius: 9 }, statValue: { fontWeight: '900', fontSize: 15 }, statLabel: { fontSize: 10, marginTop: 3 }, card: { padding: 14, borderWidth: 1, borderRadius: 10, gap: 9 }, section: { fontSize: 17, fontWeight: '900' }, input: { height: 50, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12 }, toggle: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, primary: { height: 51, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, white: { color: '#FFF', fontWeight: '900' }, visit: { minHeight: 72, padding: 13, borderWidth: 1, borderRadius: 9, flexDirection: 'row', alignItems: 'center', gap: 10 } });
