import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';
const copy = { hy: ['Նվեր քարտեր', 'Ստեղծել քարտ', 'Ստացողի անուն', 'Հեռախոս', 'Գումար՝ ֏', 'Ստեղծել', 'Չհաջողվեց', 'Քարտեր չկան'], ru: ['Подарочные карты', 'Создать карту', 'Имя получателя', 'Телефон', 'Сумма, ֏', 'Создать', 'Не удалось', 'Карт нет'], en: ['Gift cards', 'Create a card', 'Recipient name', 'Phone', 'Amount, ֏', 'Create', 'Action failed', 'No cards'] };
export default function GiftCardsScreen() { const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const [form, setForm] = useState({ name: '', phone: '', amount: '' }); const query = useQuery({ queryKey: ['business-gift-cards'], queryFn: businessApi.giftCards, retry: false }); const create = useMutation({ mutationFn: () => businessApi.createGiftCard({ amount: Number(form.amount), issued_to_name: form.name.trim(), issued_to_phone: form.phone.trim() }), onSuccess: () => { setForm({ name: '', phone: '', amount: '' }); void cache.invalidateQueries({ queryKey: ['business-gift-cards'] }); }, onError: (e) => Alert.alert(c[6], apiErrorMessage(e)) }); return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.title, { color: theme.text }]}>{c[0]}</Text><View style={[styles.form, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.formTitle, { color: theme.text }]}>{c[1]}</Text>{[c[2], c[3], c[4]].map((placeholder, i) => <TextInput key={placeholder} value={[form.name, form.phone, form.amount][i]} onChangeText={(v) => setForm((x) => ({ ...x, [i === 0 ? 'name' : i === 1 ? 'phone' : 'amount']: v }))} placeholder={placeholder} keyboardType={i ? 'phone-pad' : 'default'} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border }]} />)}<Pressable disabled={Number(form.amount) <= 0 || create.isPending} onPress={() => create.mutate()} style={[styles.button, { backgroundColor: theme.plum, opacity: Number(form.amount) > 0 ? 1 : 0.4 }]}>{create.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c[5]}</Text>}</Pressable></View>{query.isLoading ? <ActivityIndicator color={theme.plum} /> : query.data?.length ? query.data.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View><Text style={[styles.code, { color: theme.text }]}>{item.code}</Text><Text style={{ color: theme.muted }}>{item.issued_to_name ?? '—'} · {item.status}</Text></View><Text style={[styles.balance, { color: theme.plum }]}>{Number(item.balance).toLocaleString()} {item.currency}</Text></View>) : <Text style={{ color: theme.muted }}>{c[7]}</Text>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 10, paddingBottom: 35 }, title: { fontSize: 28, fontWeight: '900', marginBottom: 8 }, form: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 9 }, formTitle: { fontSize: 18, fontWeight: '900' }, input: { height: 50, borderWidth: 1, borderRadius: 9, paddingHorizontal: 13 }, button: { height: 50, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, white: { color: '#FFF', fontWeight: '900' }, card: { borderWidth: 1, borderRadius: 11, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, code: { fontWeight: '900', marginBottom: 4 }, balance: { fontWeight: '900' } });
