import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';
const copy = { hy: ['Սպասման ցուցակ', 'Սպասող հաճախորդներ չկան', 'Չեղարկել', 'Վերադարձնել սպասման մեջ', 'Չհաջողվեց'], ru: ['Лист ожидания', 'Нет ожидающих клиентов', 'Отменить', 'Вернуть в ожидание', 'Не удалось'], en: ['Waitlist', 'No waiting clients', 'Cancel', 'Return to waiting', 'Action failed'] };
export default function GrowthScreen() { const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const query = useQuery({ queryKey: ['business-waitlist'], queryFn: businessApi.waitlist, retry: false }); const update = useMutation({ mutationFn: ({ id, status }: { id: number; status: 'waiting' | 'cancelled' }) => businessApi.updateWaitlist(id, status), onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-waitlist'] }), onError: (e) => Alert.alert(c[4], apiErrorMessage(e)) }); return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: theme.text }]}>{c[0]}</Text>{query.isLoading ? <ActivityIndicator color={theme.plum} /> : query.data?.length ? query.data.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={styles.row}><View><Text style={[styles.name, { color: theme.text }]}>{item.customer_name}</Text><Text style={{ color: theme.muted }}>{item.service?.name ?? '—'} · {item.desired_date}</Text><Text style={{ color: theme.muted }}>{item.customer_phone}</Text></View><Text style={[styles.status, { color: theme.gold }]}>{item.status}</Text></View><Pressable onPress={() => update.mutate({ id: item.id, status: item.status === 'cancelled' ? 'waiting' : 'cancelled' })} style={[styles.button, { backgroundColor: item.status === 'cancelled' ? theme.plumSoft : theme.cream }]}><Text style={{ color: item.status === 'cancelled' ? theme.plum : theme.danger, fontWeight: '800' }}>{item.status === 'cancelled' ? c[3] : c[2]}</Text></Pressable></View>) : <Text style={{ color: theme.muted }}>{c[1]}</Text>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 10 }, title: { fontSize: 28, fontWeight: '900', marginBottom: 8 }, card: { borderWidth: 1, borderRadius: 11, padding: 14, gap: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, name: { fontSize: 16, fontWeight: '900', marginBottom: 4 }, status: { fontSize: 11, fontWeight: '900', textTransform: 'uppercase' }, button: { minHeight: 42, borderRadius: 8, alignItems: 'center', justifyContent: 'center' } });
