import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';
const copy = { hy: ['Հավատարմություն', 'Միացնել միավորների ծրագիրը', 'Մասնակիցներ', 'Չօգտագործված միավորներ', 'Ընդհանուր վաստակած', '30 օրում ժամկետանց', 'Չհաջողվեց'], ru: ['Лояльность', 'Включить программу баллов', 'Участники', 'Доступные баллы', 'Всего начислено', 'Истекают за 30 дней', 'Не удалось'], en: ['Loyalty', 'Enable points program', 'Members', 'Outstanding points', 'Lifetime earned', 'Expiring in 30 days', 'Action failed'] };
export default function LoyaltyScreen() { const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const summary = useQuery({ queryKey: ['loyalty-summary'], queryFn: businessApi.loyalty, retry: false }); const program = useQuery({ queryKey: ['loyalty-program'], queryFn: businessApi.loyaltyProgram, retry: false }); const toggle = useMutation({ mutationFn: (is_enabled: boolean) => businessApi.updateLoyaltyProgram({ is_enabled }), onSuccess: () => void cache.invalidateQueries({ queryKey: ['loyalty-program'] }), onError: (e) => Alert.alert(c[6], apiErrorMessage(e)) }); const data = summary.data as Record<string, unknown> | undefined; const items: [string, unknown][] = [[c[2], data?.members], [c[3], data?.outstanding_points], [c[4], data?.lifetime_earned], [c[5], data?.expiring_in_30_days]]; return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content}><Text style={[styles.title, { color: theme.text }]}>{c[0]}</Text><View style={[styles.toggle, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.toggleText, { color: theme.text }]}>{c[1]}</Text>{program.isLoading ? <ActivityIndicator color={theme.plum} /> : <Switch value={!!(program.data as Record<string, unknown>)?.is_enabled} onValueChange={(value) => toggle.mutate(value)} trackColor={{ false: theme.border, true: theme.plum }} />}</View><View style={styles.grid}>{items.map(([label, value]) => <View key={label} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.value, { color: theme.plum }]}>{String(value ?? 0)}</Text><Text style={{ color: theme.muted, fontWeight: '700' }}>{label}</Text></View>)}</View></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 14 }, title: { fontSize: 28, fontWeight: '900' }, toggle: { minHeight: 68, borderWidth: 1, borderRadius: 11, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, toggleText: { flex: 1, fontWeight: '800' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, card: { width: '48%', minHeight: 110, borderWidth: 1, borderRadius: 11, padding: 14, justifyContent: 'space-between' }, value: { fontSize: 24, fontWeight: '900' } });
