import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi, BusinessService } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

const copy = {
  hy: { title: 'Ծառայություններ', empty: 'Ծառայություններ դեռ չկան', add: 'Նոր ծառայություն', name: 'Անվանում', duration: 'Տևողություն՝ րոպե', price: 'Գին՝ ֏', save: 'Պահպանել', cancel: 'Չեղարկել', active: 'Ակտիվ', edit: 'Խմբագրել', remove: 'Ջնջել', confirm: 'Ջնջե՞լ այս ծառայությունը', error: 'Չհաջողվեց պահպանել' },
  ru: { title: 'Услуги', empty: 'Услуг пока нет', add: 'Новая услуга', name: 'Название', duration: 'Длительность, минуты', price: 'Цена, ֏', save: 'Сохранить', cancel: 'Отмена', active: 'Активна', edit: 'Изменить', remove: 'Удалить', confirm: 'Удалить эту услугу?', error: 'Не удалось сохранить' },
  en: { title: 'Services', empty: 'No services yet', add: 'New service', name: 'Name', duration: 'Duration, minutes', price: 'Price, ֏', save: 'Save', cancel: 'Cancel', active: 'Active', edit: 'Edit', remove: 'Delete', confirm: 'Delete this service?', error: 'Could not save' },
};
const blank = { name: '', duration: '60', price: '' };

export default function ServicesScreen() {
  const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient();
  const query = useQuery({ queryKey: ['business-services'], queryFn: businessApi.services, retry: false });
  const [editing, setEditing] = useState<BusinessService | null>(); const [form, setForm] = useState(blank);
  const close = () => { setEditing(undefined); setForm(blank); };
  const save = useMutation({ mutationFn: () => editing ? businessApi.updateService(editing.id, { name: form.name.trim(), duration_minutes: Number(form.duration), price: Number(form.price || 0) }) : businessApi.createService({ name: form.name.trim(), duration_minutes: Number(form.duration), price: Number(form.price || 0), currency: 'AMD' }), onSuccess: () => { close(); void cache.invalidateQueries({ queryKey: ['business-services'] }); }, onError: (error) => Alert.alert(c.error, apiErrorMessage(error)) });
  const toggle = useMutation({ mutationFn: (item: BusinessService) => businessApi.updateService(item.id, { is_active: !item.is_active }), onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-services'] }), onError: (error) => Alert.alert(c.error, apiErrorMessage(error)) });
  const remove = useMutation({ mutationFn: businessApi.deleteService, onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-services'] }), onError: (error) => Alert.alert(c.error, apiErrorMessage(error)) });
  const beginEdit = (item: BusinessService) => { setEditing(item); setForm({ name: item.name, duration: String(item.duration_minutes), price: String(item.price ?? 0) }); };
  const confirmRemove = (item: BusinessService) => Alert.alert(c.remove, c.confirm, [{ text: c.cancel, style: 'cancel' }, { text: c.remove, style: 'destructive', onPress: () => remove.mutate(item.id) }]);
  const valid = form.name.trim().length >= 2 && Number(form.duration) >= 5;

  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><View style={[styles.headerIcon, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="square.grid.2x2.fill" android="grid_view" color={theme.plum} size={25} /></View><Text style={[styles.title, { color: theme.text }]}>{c.title}</Text><Pressable onPress={() => { setEditing(null); setForm(blank); }} style={[styles.add, { backgroundColor: theme.plum }]}><VizitIcon ios="plus" android="add" color="#FFF" size={22} /></Pressable></View>
    {editing !== undefined && <View style={[styles.form, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.formTitle, { color: theme.text }]}>{editing ? c.edit : c.add}</Text><TextInput value={form.name} onChangeText={(name) => setForm((v) => ({ ...v, name }))} placeholder={c.name} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border }]} /><View style={styles.formRow}><TextInput value={form.duration} onChangeText={(duration) => setForm((v) => ({ ...v, duration }))} keyboardType="number-pad" placeholder={c.duration} placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border }]} /><TextInput value={form.price} onChangeText={(price) => setForm((v) => ({ ...v, price }))} keyboardType="number-pad" placeholder={c.price} placeholderTextColor={theme.muted} style={[styles.input, styles.flex, { color: theme.text, borderColor: theme.border }]} /></View><View style={styles.formRow}><Pressable onPress={close} style={[styles.secondary, styles.flex, { borderColor: theme.border }]}><Text style={{ color: theme.text, fontWeight: '800' }}>{c.cancel}</Text></Pressable><Pressable disabled={!valid || save.isPending} onPress={() => save.mutate()} style={[styles.primary, styles.flex, { backgroundColor: theme.plum, opacity: valid ? 1 : 0.4 }]}>{save.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c.save}</Text>}</Pressable></View></View>}
    {query.isLoading ? <ActivityIndicator color={theme.plum} /> : query.data?.length ? query.data.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={styles.cardTop}><View style={styles.body}><Text style={[styles.name, { color: theme.text }]}>{item.name}</Text><Text style={{ color: theme.muted }}>{item.duration_minutes} min · {Number(item.price).toLocaleString()} {item.currency}</Text></View><Switch value={item.is_active} onValueChange={() => toggle.mutate(item)} trackColor={{ false: theme.border, true: theme.plum }} /></View><View style={styles.actions}><Pressable onPress={() => beginEdit(item)} style={[styles.action, { backgroundColor: theme.plumSoft }]}><Text style={{ color: theme.plum, fontWeight: '800' }}>{c.edit}</Text></Pressable><Pressable onPress={() => confirmRemove(item)} style={[styles.action, { backgroundColor: theme.goldSoft }]}><Text style={{ color: theme.danger, fontWeight: '800' }}>{c.remove}</Text></Pressable></View></View>) : <Text style={{ color: theme.muted }}>{c.empty}</Text>}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 11, paddingBottom: 35 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 }, headerIcon: { width: 50, height: 50, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, title: { flex: 1, fontSize: 27, fontWeight: '900' }, add: { width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, form: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 10 }, formTitle: { fontSize: 18, fontWeight: '900' }, input: { minHeight: 51, borderWidth: 1, borderRadius: 9, paddingHorizontal: 13 }, formRow: { flexDirection: 'row', gap: 9 }, flex: { flex: 1 }, primary: { height: 49, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, secondary: { height: 49, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, white: { color: '#FFF', fontWeight: '900' }, card: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 12 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, body: { flex: 1 }, name: { fontSize: 16, fontWeight: '900', marginBottom: 4 }, actions: { flexDirection: 'row', gap: 8 }, action: { flex: 1, minHeight: 40, borderRadius: 8, alignItems: 'center', justifyContent: 'center' } });
