import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi, ScheduleDay } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

const names = { hy: ['Երկ', 'Երք', 'Չրք', 'Հնգ', 'Ուրբ', 'Շբթ', 'Կիր'], ru: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'], en: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] };
const copy = { hy: { title: 'Աշխատանքային գրաֆիկ', closed: 'Փակ', save: 'Պահպանել գրաֆիկը', saved: 'Գրաֆիկը պահպանված է', error: 'Չհաջողվեց պահպանել' }, ru: { title: 'Рабочий график', closed: 'Выходной', save: 'Сохранить график', saved: 'График сохранён', error: 'Не удалось сохранить' }, en: { title: 'Working schedule', closed: 'Closed', save: 'Save schedule', saved: 'Schedule saved', error: 'Could not save' } };
const defaults = (): ScheduleDay[] => Array.from({ length: 7 }, (_, i) => ({ weekday: i + 1, is_closed: i > 4, start: '09:00', end: '18:00', break_start: null, break_end: null }));
export default function StaffSchedule() {
  const { id, name } = useLocalSearchParams<{ id: string; name?: string }>(); const staffId = Number(id); const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const [days, setDays] = useState<ScheduleDay[]>(defaults);
  const query = useQuery({ queryKey: ['staff-schedule', staffId], queryFn: () => businessApi.staffSchedule(staffId), enabled: staffId > 0, retry: false });
  useEffect(() => { if (Array.isArray(query.data?.days) && query.data.days.length) {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setDays(defaults().map((fallback) => query.data!.days.find((item) => item.weekday === fallback.weekday) ?? fallback));
  } }, [query.data]);
  const update = (weekday: number, patch: Partial<ScheduleDay>) => setDays((current) => current.map((day) => day.weekday === weekday ? { ...day, ...patch } : day));
  const save = useMutation({ mutationFn: () => businessApi.updateStaffSchedule(staffId, days), onSuccess: () => { void cache.invalidateQueries({ queryKey: ['staff-schedule', staffId] }); Alert.alert(c.saved); }, onError: (error) => Alert.alert(c.error, apiErrorMessage(error)) });
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { borderColor: theme.border }]}><VizitIcon ios="chevron.left" android="chevron_left" color={theme.text} size={22} /></Pressable><View><Text style={[styles.title, { color: theme.text }]}>{c.title}</Text><Text style={{ color: theme.muted }}>{name}</Text></View></View>{query.isLoading ? <ActivityIndicator color={theme.plum} /> : <ScrollView contentContainerStyle={styles.content}>{days.map((day) => <View key={day.weekday} style={[styles.day, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={styles.dayTop}><Text style={[styles.dayName, { color: theme.text }]}>{names[locale][day.weekday - 1]}</Text><View style={styles.closed}><Text style={{ color: theme.muted }}>{c.closed}</Text><Switch value={day.is_closed} onValueChange={(is_closed) => update(day.weekday, { is_closed })} trackColor={{ false: theme.border, true: theme.plum }} /></View></View>{!day.is_closed && <View style={styles.times}><TextInput value={day.start ?? ''} onChangeText={(start) => update(day.weekday, { start })} placeholder="09:00" keyboardType="numbers-and-punctuation" style={[styles.time, { color: theme.text, borderColor: theme.border }]} /><Text style={{ color: theme.muted }}>—</Text><TextInput value={day.end ?? ''} onChangeText={(end) => update(day.weekday, { end })} placeholder="18:00" keyboardType="numbers-and-punctuation" style={[styles.time, { color: theme.text, borderColor: theme.border }]} /></View>}</View>)}<Pressable onPress={() => save.mutate()} style={[styles.save, { backgroundColor: theme.plum }]}>{save.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c.save}</Text>}</Pressable></ScrollView>}</SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, header: { minHeight: 74, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 42, height: 42, borderWidth: 1, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 20, fontWeight: '900' }, content: { padding: 16, gap: 9, paddingBottom: 35 }, day: { borderWidth: 1, borderRadius: 11, padding: 13, gap: 10 }, dayTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, dayName: { fontSize: 16, fontWeight: '900' }, closed: { flexDirection: 'row', alignItems: 'center', gap: 8 }, times: { flexDirection: 'row', alignItems: 'center', gap: 8 }, time: { flex: 1, height: 45, borderWidth: 1, borderRadius: 8, textAlign: 'center', fontWeight: '800' }, save: { height: 54, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, white: { color: '#FFF', fontWeight: '900' } });
