import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Href, router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

const copy = {
  hy: { title: 'Աշխատակիցներ', add: 'Ավելացնել աշխատակից', name: 'Անուն', email: 'Էլ․ փոստ', phone: 'Հեռախոս', password: 'Ժամանակավոր գաղտնաբառ', save: 'Ավելացնել', cancel: 'Չեղարկել', schedule: 'Գրաֆիկ', bookable: 'Ամրագրվող', error: 'Չհաջողվեց', empty: 'Աշխատակիցներ չկան' },
  ru: { title: 'Сотрудники', add: 'Добавить сотрудника', name: 'Имя', email: 'Эл. почта', phone: 'Телефон', password: 'Временный пароль', save: 'Добавить', cancel: 'Отмена', schedule: 'График', bookable: 'Доступен для записи', error: 'Не удалось выполнить', empty: 'Сотрудников нет' },
  en: { title: 'Team', add: 'Add team member', name: 'Name', email: 'Email', phone: 'Phone', password: 'Temporary password', save: 'Add', cancel: 'Cancel', schedule: 'Schedule', bookable: 'Bookable', error: 'Action failed', empty: 'No team members' },
};
const blank = { name: '', email: '', phone: '', password: '' };
export default function StaffScreen() {
  const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(blank);
  const query = useQuery({ queryKey: ['business-staff'], queryFn: businessApi.staff, retry: false });
  const fail = (error: unknown) => Alert.alert(c.error, apiErrorMessage(error));
  const create = useMutation({ mutationFn: () => businessApi.createStaff({ ...form, name: form.name.trim(), email: form.email.trim().toLowerCase(), phone: form.phone.trim() || undefined }), onSuccess: () => { setForm(blank); setShowForm(false); void cache.invalidateQueries({ queryKey: ['business-staff'] }); }, onError: fail });
  const active = useMutation({ mutationFn: ({ id, value }: { id: number; value: boolean }) => businessApi.setStaffActive(id, value), onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-staff'] }), onError: fail });
  const bookable = useMutation({ mutationFn: ({ id, value }: { id: number; value: boolean }) => businessApi.updateStaff(id, { is_bookable: value, show_in_public_team: value }), onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-staff'] }), onError: fail });
  const valid = form.name.trim().length >= 2 && /^\S+@\S+\.\S+$/.test(form.email) && form.password.length >= 8;
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><View style={[styles.icon, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="person.2.fill" android="group" color={theme.plum} size={25} /></View><Text style={[styles.title, { color: theme.text }]}>{c.title}</Text><Pressable onPress={() => setShowForm((v) => !v)} style={[styles.add, { backgroundColor: theme.plum }]}><VizitIcon ios="plus" android="person_add" color="#FFF" size={22} /></Pressable></View>
    {showForm && <View style={[styles.form, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.formTitle, { color: theme.text }]}>{c.add}</Text>{(['name', 'email', 'phone', 'password'] as const).map((key) => <TextInput key={key} value={form[key]} onChangeText={(value) => setForm((v) => ({ ...v, [key]: value }))} placeholder={c[key]} secureTextEntry={key === 'password'} keyboardType={key === 'email' ? 'email-address' : key === 'phone' ? 'phone-pad' : 'default'} autoCapitalize={key === 'email' ? 'none' : 'sentences'} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border }]} />)}<View style={styles.actions}><Pressable onPress={() => setShowForm(false)} style={[styles.button, styles.flex, { borderColor: theme.border }]}><Text style={{ color: theme.text, fontWeight: '800' }}>{c.cancel}</Text></Pressable><Pressable disabled={!valid || create.isPending} onPress={() => create.mutate()} style={[styles.button, styles.flex, { backgroundColor: theme.plum, opacity: valid ? 1 : 0.4 }]}>{create.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c.save}</Text>}</Pressable></View></View>}
    {query.isLoading ? <ActivityIndicator color={theme.plum} /> : query.data?.length ? query.data.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={styles.person}><View style={[styles.avatar, { backgroundColor: theme.plumSoft }]}><Text style={[styles.initial, { color: theme.plum }]}>{item.name.charAt(0).toUpperCase()}</Text></View><View style={styles.flex}><Text style={[styles.name, { color: theme.text }]}>{item.name}</Text><Text style={{ color: theme.muted, fontSize: 12 }}>{item.email} · {item.role}</Text></View><Switch value={item.is_active} onValueChange={(value) => active.mutate({ id: item.id, value })} trackColor={{ false: theme.border, true: theme.plum }} /></View><View style={styles.cardBottom}><View style={styles.bookable}><Switch value={!!item.is_bookable} onValueChange={(value) => bookable.mutate({ id: item.id, value })} trackColor={{ false: theme.border, true: theme.gold }} /><Text style={{ color: theme.text, fontWeight: '700' }}>{c.bookable}</Text></View><Pressable onPress={() => router.push(`/(business)/staff-schedule?id=${item.id}&name=${encodeURIComponent(item.name)}` as Href)} style={[styles.schedule, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="calendar" android="calendar_month" color={theme.plum} size={18} /><Text style={{ color: theme.plum, fontWeight: '800' }}>{c.schedule}</Text></Pressable></View></View>) : <Text style={{ color: theme.muted }}>{c.empty}</Text>}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 11, paddingBottom: 35 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 }, icon: { width: 50, height: 50, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, title: { flex: 1, fontSize: 27, fontWeight: '900' }, add: { width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, form: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 9 }, formTitle: { fontSize: 18, fontWeight: '900' }, input: { height: 51, borderWidth: 1, borderRadius: 9, paddingHorizontal: 13 }, actions: { flexDirection: 'row', gap: 8 }, button: { height: 48, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, white: { color: '#FFF', fontWeight: '900' }, card: { borderWidth: 1, borderRadius: 12, padding: 13, gap: 12 }, person: { flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 46, height: 46, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 19, fontWeight: '900' }, name: { fontSize: 16, fontWeight: '900', marginBottom: 3 }, cardBottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, bookable: { flexDirection: 'row', alignItems: 'center', gap: 6 }, schedule: { minHeight: 42, paddingHorizontal: 12, borderRadius: 9, flexDirection: 'row', alignItems: 'center', gap: 6 } });
