import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VizitIcon } from '@/components/vizit-icon';
import { useApp } from '@/providers/app-provider';
import { businessApi, BusinessTask } from '@/services/api/business';
import { apiErrorMessage } from '@/services/api/client';

const copy = {
  hy: { title: 'Առաջադրանքներ', add: 'Նոր առաջադրանք', name: 'Վերնագիր', description: 'Նկարագրություն', save: 'Ստեղծել', cancel: 'Չեղարկել', start: 'Սկսել', done: 'Ավարտել', remove: 'Ջնջել', empty: 'Առաջադրանքներ դեռ չկան', emptyHint: 'Ստեղծեք առաջադրանք՝ աշխատանքը թիմում չկորցնելու համար։', error: 'Գործողությունը չհաջողվեց', loadError: 'Չհաջողվեց բեռնել առաջադրանքները', retry: 'Կրկին փորձել' },
  ru: { title: 'Задачи', add: 'Новая задача', name: 'Заголовок', description: 'Описание', save: 'Создать', cancel: 'Отмена', start: 'Начать', done: 'Завершить', remove: 'Удалить', empty: 'Задач пока нет', emptyHint: 'Создайте задачу, чтобы ничего не потерялось в работе команды.', error: 'Не удалось выполнить', loadError: 'Не удалось загрузить задачи', retry: 'Повторить' },
  en: { title: 'Tasks', add: 'New task', name: 'Title', description: 'Description', save: 'Create', cancel: 'Cancel', start: 'Start', done: 'Complete', remove: 'Delete', empty: 'No tasks yet', emptyHint: 'Create a task to keep team work visible and organized.', error: 'Action failed', loadError: 'Could not load tasks', retry: 'Try again' },
};
export default function TasksScreen() {
  const { locale, theme } = useApp(); const c = copy[locale]; const cache = useQueryClient(); const [show, setShow] = useState(false); const [form, setForm] = useState({ title: '', description: '' });
  const query = useQuery({ queryKey: ['business-tasks'], queryFn: businessApi.tasks, retry: false, refetchOnMount: 'always' });
  const fail = (error: unknown) => Alert.alert(c.error, apiErrorMessage(error));
  const create = useMutation({ mutationFn: () => businessApi.createTask({ title: form.title.trim(), description: form.description.trim(), priority: 'medium' }), onSuccess: async () => { setForm({ title: '', description: '' }); setShow(false); await cache.invalidateQueries({ queryKey: ['business-tasks'] }); await cache.refetchQueries({ queryKey: ['business-tasks'], type: 'active' }); }, onError: fail });
  const update = useMutation({ mutationFn: ({ item, status }: { item: BusinessTask; status: BusinessTask['status'] }) => businessApi.updateTask(item.id, { status }), onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-tasks'] }), onError: fail });
  const remove = useMutation({ mutationFn: businessApi.deleteTask, onSuccess: () => void cache.invalidateQueries({ queryKey: ['business-tasks'] }), onError: fail });
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><View style={[styles.icon, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="checklist" android="task_alt" color={theme.plum} size={25} /></View><Text style={[styles.title, { color: theme.text }]}>{c.title}</Text><Pressable onPress={() => setShow((value) => !value)} style={[styles.add, { backgroundColor: theme.plum }]}><VizitIcon ios={show ? 'xmark' : 'plus'} android={show ? 'close' : 'add'} color="#FFF" size={22} /></Pressable></View>
    {show && <View style={[styles.form, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><Text style={[styles.formTitle, { color: theme.text }]}>{c.add}</Text><TextInput value={form.title} onChangeText={(title) => setForm((v) => ({ ...v, title }))} placeholder={c.name} placeholderTextColor={theme.muted} style={[styles.input, { color: theme.text, borderColor: theme.border }]} /><TextInput value={form.description} onChangeText={(description) => setForm((v) => ({ ...v, description }))} placeholder={c.description} placeholderTextColor={theme.muted} multiline style={[styles.input, styles.multiline, { color: theme.text, borderColor: theme.border }]} /><View style={styles.actions}><Pressable onPress={() => setShow(false)} style={[styles.button, styles.flex, { borderColor: theme.border }]}><Text style={{ color: theme.text, fontWeight: '800' }}>{c.cancel}</Text></Pressable><Pressable disabled={form.title.trim().length < 2 || create.isPending} onPress={() => create.mutate()} style={[styles.button, styles.flex, { backgroundColor: theme.plum, opacity: form.title.trim().length >= 2 ? 1 : 0.4 }]}>{create.isPending ? <ActivityIndicator color="#FFF" /> : <Text style={styles.white}>{c.save}</Text>}</Pressable></View></View>}
    {query.isLoading ? <ActivityIndicator color={theme.plum} /> : query.isError ? <View style={[styles.error, { borderColor: theme.border, backgroundColor: theme.surfaceRaised }]}><VizitIcon ios="exclamationmark.triangle.fill" android="error_outline" color={theme.danger} size={25} /><Text style={{ color: theme.text, fontWeight: '900' }}>{c.loadError}</Text><Text style={{ color: theme.muted, fontSize: 12, textAlign: 'center' }}>{apiErrorMessage(query.error)}</Text><Pressable onPress={() => query.refetch()}><Text style={{ color: theme.plum, fontWeight: '900' }}>{c.retry}</Text></Pressable></View> : query.data?.length ? query.data.map((item) => <View key={item.id} style={[styles.card, { backgroundColor: theme.surfaceRaised, borderColor: theme.border }]}><View style={styles.taskTop}><View style={[styles.priority, { backgroundColor: item.priority === 'urgent' ? theme.dangerSoft : theme.plumSoft }]}><Text style={{ color: item.priority === 'urgent' ? theme.danger : theme.plum, fontWeight: '900', fontSize: 10 }}>{item.priority}</Text></View><Text style={[styles.status, { color: theme.muted }]}>{item.status.replace('_', ' ')}</Text></View><Text style={[styles.taskTitle, { color: theme.text }]}>{item.title}</Text>{item.description ? <Text style={{ color: theme.muted }}>{item.description}</Text> : null}<View style={styles.actions}>{item.status === 'open' && <Pressable onPress={() => update.mutate({ item, status: 'in_progress' })} style={[styles.smallButton, { backgroundColor: theme.plumSoft }]}><Text style={{ color: theme.plum, fontWeight: '800' }}>{c.start}</Text></Pressable>}{item.status !== 'completed' && <Pressable onPress={() => update.mutate({ item, status: 'completed' })} style={[styles.smallButton, { backgroundColor: theme.successSoft }]}><Text style={{ color: theme.success, fontWeight: '800' }}>{c.done}</Text></Pressable>}<Pressable onPress={() => remove.mutate(item.id)} style={[styles.smallButton, { backgroundColor: theme.cream }]}><Text style={{ color: theme.danger, fontWeight: '800' }}>{c.remove}</Text></Pressable></View></View>) : <View style={[styles.empty, { borderColor: theme.border, backgroundColor: theme.surfaceRaised }]}><View style={[styles.emptyIcon, { backgroundColor: theme.plumSoft }]}><VizitIcon ios="checklist" android="task_alt" color={theme.plum} size={31} /></View><Text style={[styles.emptyTitle, { color: theme.text }]}>{c.empty}</Text><Text style={[styles.emptyHint, { color: theme.muted }]}>{c.emptyHint}</Text><Pressable onPress={() => setShow(true)} style={[styles.emptyCta, { backgroundColor: theme.plum }]}><VizitIcon ios="plus" android="add" color="#FFF" size={18} /><Text style={styles.white}>{c.add}</Text></Pressable></View>}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, gap: 10, paddingBottom: 35 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 }, icon: { width: 50, height: 50, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, title: { flex: 1, fontSize: 27, fontWeight: '900' }, add: { width: 44, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, form: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 9 }, formTitle: { fontSize: 18, fontWeight: '900' }, input: { minHeight: 51, borderWidth: 1, borderRadius: 9, paddingHorizontal: 13 }, multiline: { height: 84, paddingTop: 13, textAlignVertical: 'top' }, actions: { flexDirection: 'row', gap: 7 }, button: { height: 48, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, white: { color: '#FFF', fontWeight: '900' }, card: { borderWidth: 1, borderRadius: 12, padding: 14, gap: 8 }, taskTop: { flexDirection: 'row', justifyContent: 'space-between' }, priority: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 7 }, status: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, taskTitle: { fontSize: 16, fontWeight: '900' }, smallButton: { flex: 1, minHeight: 39, borderRadius: 8, alignItems: 'center', justifyContent: 'center', padding: 5 }, error: { borderWidth: 1, borderRadius: 11, padding: 18, gap: 8, alignItems: 'center' }, empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 12, padding: 26, alignItems: 'center', gap: 9 }, emptyIcon: { width: 58, height: 58, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { fontSize: 18, fontWeight: '900', textAlign: 'center' }, emptyHint: { textAlign: 'center', lineHeight: 19 }, emptyCta: { minHeight: 46, borderRadius: 9, paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, marginTop: 5 } });