import { publicClient } from './client';
export type Location = { id: number; name: string; address?: string | null; lat?: number; lng?: number };
export type PublicBusiness = { business_id: number; name: string; slug: string; category_name?: string | null; address?: string | null; phone?: string | null; description?: string | null; short_description?: string | null; cover_url?: string | null; logo_url?: string | null; locations: Location[] };
export type Service = { id: number; name: string; description?: string | null; duration_minutes: number; price: number; currency: string; image_url?: string | null };
export type Staff = { id: number; name: string; role?: string; avatar_url?: string | null; bio?: string | null };
export type Slot = { starts_at: string; ends_at: string; staff_id: number; staff_name: string; is_recommended?: boolean };
const mediaUrl = (value?: string | null) => value?.startsWith('/') ? `https://api.vizit.am${value}` : value ?? null;
function normalizeBusiness(v: Record<string, unknown>): PublicBusiness { return { business_id: Number(v.business_id ?? v.id), name: String(v.name ?? ''), slug: String(v.slug ?? ''), category_name: v.category_name == null ? null : String(v.category_name), address: v.address == null ? null : String(v.address), phone: v.phone == null ? null : String(v.phone), description: v.description == null ? null : String(v.description), short_description: v.short_description == null ? null : String(v.short_description), cover_url: mediaUrl(v.cover_url as string | null), logo_url: mediaUrl(v.logo_url as string | null), locations: Array.isArray(v.locations) ? v.locations as Location[] : [] }; }
function normalize(payload: unknown): PublicBusiness[] { const root = payload as { data?: unknown; businesses?: unknown }; const list = Array.isArray(root) ? root : Array.isArray(root?.data) ? root.data : Array.isArray(root?.businesses) ? root.businesses : []; return (list as Record<string, unknown>[]).map(normalizeBusiness).filter((v) => v.slug && v.name); }
export const publicApi = {
  async businesses(params?: { locale?: string; search?: string }) { for (const path of ['/v1/public/businesses', '/public/businesses']) { try { const { data } = await publicClient.get(path, { params }); return normalize(data); } catch (error) { if (path.startsWith('/public')) throw error; } } return []; },
  business: async (slug: string) => normalizeBusiness((await publicClient.get(`/v1/public/businesses/${slug}`)).data),
  services: async (slug: string, locationId?: number): Promise<Service[]> => { const { data } = await publicClient.get(`/public/businesses/${slug}/services`, { params: { location_id: locationId } }); return (data.data ?? data).map((item: Service) => ({ ...item, image_url: mediaUrl(item.image_url) })); },
  staff: async (slug: string, locationId?: number): Promise<Staff[]> => { const { data } = await publicClient.get(`/public/businesses/${slug}/staff`, { params: { location_id: locationId } }); return (data.data ?? data).map((item: Staff) => ({ ...item, avatar_url: mediaUrl(item.avatar_url) })); },
  availability: async (slug: string, params: { date: string; service_id: number; staff_id?: number; location_id?: number }): Promise<Slot[]> => { const { data } = await publicClient.get(`/public/businesses/${slug}/availability`, { params: { ...params, _t: Date.now() } }); return data.data ?? data; },
  createBooking: async (slug: string, payload: Record<string, unknown>) => (await publicClient.post(`/public/businesses/${slug}/bookings`, payload)).data,
  verifyBooking: async (bookingCode: string, otp: string) => (await publicClient.post(`/public/bookings/${bookingCode}/verify`, { otp })).data,
  resendBookingOtp: async (bookingCode: string) => (await publicClient.post(`/public/bookings/${bookingCode}/resend`)).data,
  booking: async (bookingCode: string, guestToken: string) => (await publicClient.get(`/public/bookings/${bookingCode}`, { headers: { 'X-Guest-Token': guestToken } })).data,
  telegramLink: async (bookingCode: string, guestToken: string): Promise<{ url: string }> => { const { data } = await publicClient.post(`/public/bookings/${bookingCode}/telegram-link`, {}, { headers: { 'X-Guest-Token': guestToken } }); return data.data ?? data; },
  cancelBooking: async (bookingCode: string, guestToken: string) => (await publicClient.post(`/public/bookings/${bookingCode}/cancel`, {}, { headers: { 'X-Guest-Token': guestToken } })).data,
  rescheduleOptions: async (bookingCode: string, guestToken: string, params: { booking_id: number; date: string; staff_id?: number }) => (await publicClient.get(`/public/bookings/${bookingCode}/reschedule-options`, { params, headers: { 'X-Guest-Token': guestToken } })).data,
  rescheduleBooking: async (bookingCode: string, guestToken: string, payload: { booking_id: number; staff_id: number; starts_at: string }) => (await publicClient.post(`/public/bookings/${bookingCode}/reschedule`, payload, { headers: { 'X-Guest-Token': guestToken } })).data,
  createDepositSession: async (bookingCode: string, guestToken: string, payload: { return_url: string; cancel_url: string }) => (await publicClient.post(`/public/bookings/${bookingCode}/payments/idbank/session`, payload, { headers: { 'X-Guest-Token': guestToken } })).data,
  paymentCapabilities: async (bookingCode: string, guestToken: string) => (await publicClient.get(`/public/bookings/${bookingCode}/payments/capabilities`, { headers: { 'X-Guest-Token': guestToken } })).data,
  paymentStatus: async (bookingCode: string, paymentId: string, guestToken: string) => (await publicClient.get(`/public/bookings/${bookingCode}/payments/${paymentId}/status`, { headers: { 'X-Guest-Token': guestToken } })).data,
};
