import { router, useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useApp } from '@/providers/app-provider';
import { VizitIcon } from '@/components/vizit-icon';
import { guestBookingStore } from '@/services/guest-booking-store';
import { publicApi } from '@/services/api/public';

export default function PaymentReturnScreen() {
  const params = useLocalSearchParams<{ status?: string; invoice_id?: string }>(); const { locale, theme } = useApp();
  const [session, setSession] = useState<{ code: string; token: string } | null>(null);
  useEffect(() => { guestBookingStore.restoreLast().then(setSession); }, []);
  const verified = useQuery({ queryKey: ['booking-payment', session?.code, params.invoice_id], queryFn: () => publicApi.paymentStatus(session!.code, params.invoice_id!, session!.token), enabled: Boolean(session && params.invoice_id), retry: 2, refetchInterval: (query) => query.state.data?.data?.status === 'pending' ? 2000 : false });
  const serverStatus = verified.data?.data?.status;
  const status = serverStatus === 'paid' ? 'success' : serverStatus === 'failed' ? 'failed' : serverStatus === 'cancelled' ? 'cancelled' : 'processing';
  const copy = { hy: { processing: ['Վճարումը ստուգվում է', 'Բանկի վերադարձը վերջնական հաստատում չէ․ սերվերը պետք է հաստատի կարգավիճակը։'], success: ['Բանկը վերադարձրել է հաջող արդյունք', 'Վերջնական կարգավիճակը հաստատվում է Vizit սերվերի կողմից։'], failed: ['Վճարումը չհաստատվեց', 'Կարող ես նորից փորձել ամրագրման բաժնից։'], cancelled: ['Վճարումը չեղարկվեց', 'Գործարքը փակվել է առանց վճարման։'], back: 'Վերադառնալ ամրագրումներին' }, ru: { processing: ['Проверяем платёж', 'Возврат из банка не является окончательным подтверждением. Статус проверяет сервер.'], success: ['Банк вернул успешный результат', 'Окончательный статус подтверждается сервером Vizit.'], failed: ['Платёж не подтверждён', 'Попробуйте снова из раздела записей.'], cancelled: ['Платёж отменён', 'Операция закрыта без оплаты.'], back: 'Вернуться к записям' }, en: { processing: ['Checking payment', 'Returning from the bank is not final confirmation. The server verifies the status.'], success: ['The bank returned success', 'The Vizit server confirms the final status.'], failed: ['Payment was not confirmed', 'Try again from your bookings.'], cancelled: ['Payment cancelled', 'The transaction closed without payment.'], back: 'Back to bookings' } }[locale];
  const [title, body] = copy[status];
  const icon = status === 'success' ? { ios: 'checkmark.circle.fill' as const, android: 'check_circle' as const, color: theme.success } : status === 'failed' ? { ios: 'xmark.circle.fill' as const, android: 'cancel' as const, color: theme.danger } : status === 'cancelled' ? { ios: 'minus.circle.fill' as const, android: 'do_not_disturb_on' as const, color: theme.muted } : { ios: 'clock.badge.questionmark.fill' as const, android: 'pending' as const, color: theme.gold };
  return <SafeAreaView style={[styles.screen, { backgroundColor: theme.background }]}><View style={[styles.card, { backgroundColor: theme.surface, shadowColor: theme.shadow }]}><View style={[styles.iconWrap, { backgroundColor: theme.plumSoft }]}><VizitIcon ios={icon.ios} android={icon.android} color={icon.color} size={44} /></View><Text style={[styles.title, { color: theme.text }]}>{title}</Text><Text style={[styles.body, { color: theme.muted }]}>{body}</Text><Pressable onPress={() => router.replace('/(customer)/bookings')} style={[styles.button, { backgroundColor: theme.plum }]}><Text style={styles.buttonText}>{copy.back}</Text><VizitIcon ios="arrow.right" android="arrow_forward" color="#FFFFFF" size={18} /></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, justifyContent: 'center', padding: 20 }, card: { padding: 24, borderRadius: 27, alignItems: 'center', gap: 13, shadowOpacity: 0.08, shadowRadius: 18, shadowOffset: { width: 0, height: 6 }, elevation: 3 }, iconWrap: { width: 78, height: 78, borderRadius: 27, alignItems: 'center', justifyContent: 'center', marginBottom: 3 }, title: { fontSize: 24, fontWeight: '900', letterSpacing: -0.4, textAlign: 'center' }, body: { fontSize: 14, lineHeight: 22, textAlign: 'center' }, button: { alignSelf: 'stretch', height: 54, borderRadius: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, marginTop: 8 }, buttonText: { color: '#FFF', fontWeight: '900' } });
